/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-security-documentation.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../raml-aware/raml-aware.d.ts" />
/// <reference path="../markdown-styles/markdown-styles.d.ts" />
/// <reference path="../marked-element/marked-element.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../api-annotation-document/api-annotation-document.d.ts" />
/// <reference path="../api-parameters-document/api-parameters-document.d.ts" />
/// <reference path="../api-headers-document/api-headers-document.d.ts" />
/// <reference path="../api-responses-document/api-responses-document.d.ts" />
/// <reference path="../amf-helper-mixin/amf-helper-mixin.d.ts" />
/// <reference path="api-oauth2-settings-document.d.ts" />
/// <reference path="api-oauth1-settings-document.d.ts" />

declare namespace ApiElements {

  /**
   * `api-security-documentation`
   *
   * Documentation view for AMF security description
   *
   * ## Styling
   *
   * `<api-security-documentation>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-security-documentation` | Mixin applied to this elment | `{}`
   * `--arc-font-headline` | Theme mixin, Applied to H1 element | `{}`
   * `--api-security-documentation-title` | Mixin applied to the H1 element | `{}`
   * `--api-security-documentation-title-narrow` | Mixin applied to the H1 element in narrow layout | `{}`
   * `--arc-font-title` | Theme mixin, applied to h2 element | `{}`
   * `--api-security-documentation-main-section-title` | Mixin applied to main sections title element | `{}`
   * `--api-security-documentation-main-section-title-narrow` | Mixin applied to main sections title element in narrow layout | `{}`
   */
  class ApiSecurityDocumentation extends
    ApiElements.AmfHelperMixin(
    Object) {

    /**
     * `raml-aware` scope property to use.
     */
    aware: string|null|undefined;

    /**
     * A security definition to render.
     * This should be AMF's type of `http://raml.org/vocabularies/security#SecurityScheme`.
     */
    security: object|null;

    /**
     * Computed value, scheme of the security
     */
    readonly _scheme: object|null|undefined;

    /**
     * Security scheme type.
     */
    readonly _type: string|null|undefined;
    readonly _description: string|null|undefined;
    readonly _hasDescription: boolean|null|undefined;
    readonly _headers: any[]|null|undefined;
    readonly _hasHeaders: any[]|null|undefined;
    readonly _queryParameters: any[]|null|undefined;
    readonly _hasQueryParameters: any[]|null|undefined;
    readonly _responses: any[]|null|undefined;
    readonly _hasResponses: any[]|null|undefined;
    readonly _settings: any[]|null|undefined;
    readonly _hasSettings: any[]|null|undefined;
    readonly _hasOA2Settings: boolean|null|undefined;
    readonly _hasOA1Settings: boolean|null|undefined;

    /**
     * Computed value from current `method`. True if the model contains
     * custom properties (annotations in RAML).
     */
    readonly hasCustomProperties: boolean|null|undefined;

    /**
     * Set to render a mobile friendly view.
     */
    narrow: boolean|null|undefined;
    _computeType(shape: any): any;
    _computeScheme(security: any): any;
    _computeSettings(shape: any): any;
    _computeHasOA2Settings(hasSettings: any, settings: any): any;
    _computeHasOA1Settings(hasSettings: any, settings: any): any;
  }
}

interface HTMLElementTagNameMap {
  "api-security-documentation": ApiElements.ApiSecurityDocumentation;
}
