/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-oauth1-settings-document.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../markdown-styles/markdown-styles.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../amf-helper-mixin/amf-helper-mixin.d.ts" />

declare namespace ApiElements {

  /**
   * `api-oauth1-settings-document`
   *
   * Documentation view for AMF OAuth2 security settings
   *
   * ## Styling
   *
   * `<api-oauth1-settings-document>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-oauth1-settings-document` | Mixin applied to this elment | `{}`
   */
  class ApiOauth1SettingsDocument extends
    ApiElements.AmfHelperMixin(
    Object) {
    settings: object|null|undefined;

    /**
     * Computed value from current `method`. True if the model contains
     * custom properties (annotations in RAML).
     */
    readonly hasCustomProperties: boolean|null|undefined;
    readonly requestTokenUri: string|null|undefined;
    readonly hasRequestTokenUri: boolean|null|undefined;
    readonly authorizationUri: string|null|undefined;
    readonly hasAuthorizationUri: boolean|null|undefined;
    readonly tokenCredentialsUri: string|null|undefined;
    readonly hasTokenCredentialsUri: boolean|null|undefined;
    readonly signatures: any[]|null|undefined;
    readonly hasSignatures: boolean|null|undefined;
    _computeRequestTokenUri(settings: any): any;
    _computeAuthorizationUri(settings: any): any;
    _computeTokenCredentialsUri(settings: any): any;
    _computeSignatures(settings: any): any;
  }
}

interface HTMLElementTagNameMap {
  "api-oauth1-settings-document": ApiElements.ApiOauth1SettingsDocument;
}
