swagger: "2.0"
info:
  version: "1.0.0"
  title: Swagger Petstore

securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/api/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets

paths:
  /pets:
    delete:
      tags:
        - pets
      summary: Deletes a pet
      responses:
        "204":
          description: Pet deleted
      security:
        - petstore_auth:
            - write:pets